require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecEventFollowsController do

  # This should return the minimal set of attributes required to create a valid
  # RecEventFollow. As you add validations to RecEventFollow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "recurring_event_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecEventFollowsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rec_event_follows as @rec_event_follows" do
      rec_event_follow = RecEventFollow.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rec_event_follows).should eq([rec_event_follow])
    end
  end

  describe "GET show" do
    it "assigns the requested rec_event_follow as @rec_event_follow" do
      rec_event_follow = RecEventFollow.create! valid_attributes
      get :show, {:id => rec_event_follow.to_param}, valid_session
      assigns(:rec_event_follow).should eq(rec_event_follow)
    end
  end

  describe "GET new" do
    it "assigns a new rec_event_follow as @rec_event_follow" do
      get :new, {}, valid_session
      assigns(:rec_event_follow).should be_a_new(RecEventFollow)
    end
  end

  describe "GET edit" do
    it "assigns the requested rec_event_follow as @rec_event_follow" do
      rec_event_follow = RecEventFollow.create! valid_attributes
      get :edit, {:id => rec_event_follow.to_param}, valid_session
      assigns(:rec_event_follow).should eq(rec_event_follow)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecEventFollow" do
        expect {
          post :create, {:rec_event_follow => valid_attributes}, valid_session
        }.to change(RecEventFollow, :count).by(1)
      end

      it "assigns a newly created rec_event_follow as @rec_event_follow" do
        post :create, {:rec_event_follow => valid_attributes}, valid_session
        assigns(:rec_event_follow).should be_a(RecEventFollow)
        assigns(:rec_event_follow).should be_persisted
      end

      it "redirects to the created rec_event_follow" do
        post :create, {:rec_event_follow => valid_attributes}, valid_session
        response.should redirect_to(RecEventFollow.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rec_event_follow as @rec_event_follow" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecEventFollow.any_instance.stub(:save).and_return(false)
        post :create, {:rec_event_follow => { "recurring_event_id" => "invalid value" }}, valid_session
        assigns(:rec_event_follow).should be_a_new(RecEventFollow)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecEventFollow.any_instance.stub(:save).and_return(false)
        post :create, {:rec_event_follow => { "recurring_event_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rec_event_follow" do
        rec_event_follow = RecEventFollow.create! valid_attributes
        # Assuming there are no other rec_event_follows in the database, this
        # specifies that the RecEventFollow created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecEventFollow.any_instance.should_receive(:update).with({ "recurring_event_id" => "1" })
        put :update, {:id => rec_event_follow.to_param, :rec_event_follow => { "recurring_event_id" => "1" }}, valid_session
      end

      it "assigns the requested rec_event_follow as @rec_event_follow" do
        rec_event_follow = RecEventFollow.create! valid_attributes
        put :update, {:id => rec_event_follow.to_param, :rec_event_follow => valid_attributes}, valid_session
        assigns(:rec_event_follow).should eq(rec_event_follow)
      end

      it "redirects to the rec_event_follow" do
        rec_event_follow = RecEventFollow.create! valid_attributes
        put :update, {:id => rec_event_follow.to_param, :rec_event_follow => valid_attributes}, valid_session
        response.should redirect_to(rec_event_follow)
      end
    end

    describe "with invalid params" do
      it "assigns the rec_event_follow as @rec_event_follow" do
        rec_event_follow = RecEventFollow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecEventFollow.any_instance.stub(:save).and_return(false)
        put :update, {:id => rec_event_follow.to_param, :rec_event_follow => { "recurring_event_id" => "invalid value" }}, valid_session
        assigns(:rec_event_follow).should eq(rec_event_follow)
      end

      it "re-renders the 'edit' template" do
        rec_event_follow = RecEventFollow.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecEventFollow.any_instance.stub(:save).and_return(false)
        put :update, {:id => rec_event_follow.to_param, :rec_event_follow => { "recurring_event_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rec_event_follow" do
      rec_event_follow = RecEventFollow.create! valid_attributes
      expect {
        delete :destroy, {:id => rec_event_follow.to_param}, valid_session
      }.to change(RecEventFollow, :count).by(-1)
    end

    it "redirects to the rec_event_follows list" do
      rec_event_follow = RecEventFollow.create! valid_attributes
      delete :destroy, {:id => rec_event_follow.to_param}, valid_session
      response.should redirect_to(rec_event_follows_url)
    end
  end

end
