require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecurringEventsController do

  # This should return the minimal set of attributes required to create a valid
  # RecurringEvent. As you add validations to RecurringEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecurringEventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recurring_events as @recurring_events" do
      recurring_event = RecurringEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recurring_events).should eq([recurring_event])
    end
  end

  describe "GET show" do
    it "assigns the requested recurring_event as @recurring_event" do
      recurring_event = RecurringEvent.create! valid_attributes
      get :show, {:id => recurring_event.to_param}, valid_session
      assigns(:recurring_event).should eq(recurring_event)
    end
  end

  describe "GET new" do
    it "assigns a new recurring_event as @recurring_event" do
      get :new, {}, valid_session
      assigns(:recurring_event).should be_a_new(RecurringEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested recurring_event as @recurring_event" do
      recurring_event = RecurringEvent.create! valid_attributes
      get :edit, {:id => recurring_event.to_param}, valid_session
      assigns(:recurring_event).should eq(recurring_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecurringEvent" do
        expect {
          post :create, {:recurring_event => valid_attributes}, valid_session
        }.to change(RecurringEvent, :count).by(1)
      end

      it "assigns a newly created recurring_event as @recurring_event" do
        post :create, {:recurring_event => valid_attributes}, valid_session
        assigns(:recurring_event).should be_a(RecurringEvent)
        assigns(:recurring_event).should be_persisted
      end

      it "redirects to the created recurring_event" do
        post :create, {:recurring_event => valid_attributes}, valid_session
        response.should redirect_to(RecurringEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recurring_event as @recurring_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringEvent.any_instance.stub(:save).and_return(false)
        post :create, {:recurring_event => { "name" => "invalid value" }}, valid_session
        assigns(:recurring_event).should be_a_new(RecurringEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringEvent.any_instance.stub(:save).and_return(false)
        post :create, {:recurring_event => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recurring_event" do
        recurring_event = RecurringEvent.create! valid_attributes
        # Assuming there are no other recurring_events in the database, this
        # specifies that the RecurringEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecurringEvent.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => recurring_event.to_param, :recurring_event => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested recurring_event as @recurring_event" do
        recurring_event = RecurringEvent.create! valid_attributes
        put :update, {:id => recurring_event.to_param, :recurring_event => valid_attributes}, valid_session
        assigns(:recurring_event).should eq(recurring_event)
      end

      it "redirects to the recurring_event" do
        recurring_event = RecurringEvent.create! valid_attributes
        put :update, {:id => recurring_event.to_param, :recurring_event => valid_attributes}, valid_session
        response.should redirect_to(recurring_event)
      end
    end

    describe "with invalid params" do
      it "assigns the recurring_event as @recurring_event" do
        recurring_event = RecurringEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => recurring_event.to_param, :recurring_event => { "name" => "invalid value" }}, valid_session
        assigns(:recurring_event).should eq(recurring_event)
      end

      it "re-renders the 'edit' template" do
        recurring_event = RecurringEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecurringEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => recurring_event.to_param, :recurring_event => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recurring_event" do
      recurring_event = RecurringEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => recurring_event.to_param}, valid_session
      }.to change(RecurringEvent, :count).by(-1)
    end

    it "redirects to the recurring_events list" do
      recurring_event = RecurringEvent.create! valid_attributes
      delete :destroy, {:id => recurring_event.to_param}, valid_session
      response.should redirect_to(recurring_events_url)
    end
  end

end
